### ISSUE TITLE
move cifsd-team/cifsd to cifsd-team/cifsd-old and move namjaejeon/cifsd to cifsd-team/cifsd

### ISSUE THREAD

**Issue by Neustradamus** [cifsd-team/cifsd#103]
First, it is possible to move cifsd-team/cifsd to cifsd-team/cifsd-archives (or cifsd-team/cifsd-old)
and move namjaejeon/cifsd to cifsd-team/cifsd

It will be better, I do not understand the fork ;)

https://help.github.com/articles/about-repository-transfers/

Linked to https://github.com/namjaejeon/cifsd/issues/236

**Comment by sergey-senozhatsky** [comment]
Hi @Neustradamus 

We'll take a look sometime in the future. Thanks!

-ss

**Comment by Neustradamus** [comment]
@cifsd-team, @sergey-senozhatsky: Any news?

**Comment by Neustradamus** [comment]
@namjaejeon, @cifsd-team, @sergey-senozhatsky, @launius, @hclee: 5 minutes less to do it by repository ;)

**Comment by Neustradamus** [comment]
@namjaejeon, @cifsd-team, @sergey-senozhatsky, @launius, @hclee: 5 minutes less to do it by repository ;)

**Comment by Neustradamus** [comment]
namjaejeon: Why have you closed this ticket without solution?

**Comment by Neustradamus** [comment]
@namjaejeon: I am happy, I am not alone to see the difference and problem between personnal account vs organization.

@pali has confirmed the problem several months ago (pali commented on 12 Apr 2020):
- https://github.com/namjaejeon/exfatprogs/issues/18#issuecomment-612531558

@ptpt52 has confirmed the problem here too and specified you a little solution (ptpt52 commented on 3 Feb 2021):
- https://github.com/cifsd-team/cifsd/issues/471#issuecomment-772587252
- https://github.com/cifsd-team/cifsd/issues/471#issuecomment-772591033

All of us, I think try to help you to have perfect products...

Another solution is to detach organization repositories from personal account repositories:
- https://support.github.com/contact?tags=rr-forks

Thanks in advance.
