### ISSUE TITLE
Error on MiXplorer with SMB2 plugin

### ISSUE THREAD

**Issue by dengqf6** [cifsd-team/cifsd#117]

**Comment by gibeomii-kim** [comment]
hello, 
Can you tell which version of the app you used?
As I checked, the free version of Mixplorer, but I think it only supports SMB1.
Can you tell me what you mean by "SMB2 plugin"?

**Comment by gibeomii-kim** [comment]
I checked, it doesn't work in Windows as well as cifsd.
I think it is not a problem of cifsd but an issue of app.

**Comment by namjaejeon** [comment]
Hm... No response, So close.
