### ISSUE TITLE
Weird Nextcloud issue

### ISSUE THREAD

**Issue by neheb** [cifsd-team/cifsd#138]
```
[335455.275029] kcifsd: smb2_query_dir:3058: no right to enumerate directory (._sync_8b190b77401f.db)
```

That's not a directory.

Versions:
cifsd-tools - 2019-06-17-81e4ff30-1
kmod-fs-cifsd - 4.14.130+2019-06-24-aaa7844e-1

edit: I should note. Behavior is that the share gets frozen for maybe a minute if not longer, after which it throws the error and continues working. This is a little endian device.

**Comment by namjaejeon** [comment]
It is correct that cifsd return ACCESS DENIED error response if file is not directory. and it is defined in smb specification. Same symptom happen with samba ? or no issue with samba ?

**Comment by neheb** [comment]
Have not tested with Samba.

**Comment by namjaejeon** [comment]
Okay, Want to know same issue doesn't happen with windows or samba. because want to compare packets. If same issue happen with windows and samba, I think that it will be Nextcloud issue.

**Comment by neheb** [comment]
Closing as IIRC, it was a cosmetic issue.
