### ISSUE TITLE
Cannot mount share when running under Big Endian system

### ISSUE THREAD

**Issue by neheb** [cifsd-team/cifsd#14]
On a little endian MIPS device, no problems.

On a big endian MIPS device, mounting locally or remotely results in

```
mount: mounting //127.0.0.1/Music on test failed: I/O error
```

The setup uses the same smb.conf file, same cifsdb file, and same filesystem (ext4).

/etc/passwd, /etc/group, and /etc/shadow have identical users.

Filesystem paths are the same (rsync'ed from one to the other).

mount.cifs version is 6.8 locally (router) and remotely (laptop).

dmesg output when cifsd_debugging is turned on: https://gist.github.com/neheb/a45f8e36480d532482f31ad0d3b53fae

When mounting with vers=3.0, output is slighly different:

```
Sun Mar  3 13:34:21 2019 kern.err kernel: [43840.583631] kcifsd: cifsd_lookup_dialect_by_id:237: client requested dialect 0x300
Sun Mar  3 13:34:21 2019 kern.err kernel: [43840.591350] kcifsd: cifsd_smb_negotiate_common:496: conn->dialect 0xffff
Sun Mar  3 13:34:21 2019 kern.err kernel: [43840.598172] kcifsd: smb2_handle_negotiate:849: Recieved negotiate request
Sun Mar  3 13:34:21 2019 kern.err kernel: [43840.605110] kcifsd: smb2_handle_negotiate:914: Server dialect :0xffff not supported
Sun Mar  3 13:34:21 2019 kern.err kernel: [43840.612929] kcifsd: __process_request:167: Failed to process 0 [-22]
Sun Mar  3 13:34:21 2019 kern.err kernel: [43840.619392] kcifsd: smb2_set_rsp_credits:544: credits: requested[2] granted[1] total_granted[1]
```

There is actually an extra message that I left out at the end of both outputs that I believed was unrelated, but it might be.

```
Sun Mar  3 13:34:21 2019 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
```

Error -5 is I/O error which matches the mount error. Looks like some netlink issue.

**Comment by namjaejeon** [comment]
@neheb We don't have big endian device now.
So it is helpful if you send debug log message after it is enable.

1. debug log message enable.
echo 1 > /sys/module/cifs_server/parameters/cifsd_debugging

2. You can reproduce issue and share the full log message from cifsd with me!

Thanks for your work!

**Comment by neheb** [comment]
dmesg output was provided above with cifs_debugging enabled.

I can provide SSH access if needed.

**Comment by sergey-senozhatsky** [comment]
Seems like we are doing double le16_to_cpu() conversion.

-ss

**Comment by sergey-senozhatsky** [comment]
Probably something like this will help?

---
diff --git a/smb_common.c b/smb_common.c
index 7789ff2..5ef7da4 100644
--- a/smb_common.c
+++ b/smb_common.c
@@ -260,7 +260,7 @@ int cifsd_negotiate_smb_dialect(void *buf)
 
                req = (struct smb2_negotiate_req *)buf;
                return cifsd_lookup_dialect_by_id(req->Dialects,
-                                       le16_to_cpu(req->DialectCount));
+                                                 req->DialectCount);
        }
 
        proto = *(__le32 *)((struct smb_hdr *)buf)->Protocol;
@@ -269,7 +269,7 @@ int cifsd_negotiate_smb_dialect(void *buf)
 
                req = (NEGOTIATE_REQ *)buf;
                return cifsd_lookup_dialect_by_name(req->DialectsArray,
-                                       le16_to_cpu(req->ByteCount));
+                                                   req->ByteCount);
        }
 
        return BAD_PROT_ID;
---

**Comment by namjaejeon** [comment]
@neheb You can close it if you think all big endian issues are clear.

Thanks for your work and help!
