### ISSUE TITLE
new write premission error?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd#149]
Seems something in the latest git broke writes? We can read fine but any write attempt fails, without any extra error in the logs. I use the exact same config that worked before?

```
[global]
	netbios name = router
	server string = Cifsd on OpenWrt
	workgroup = WORKGROUP
	interfaces = br-lan lo 
	bind interfaces only = yes
	ipc timeout = 8
	deadtime = 15
	map to guest = Bad User

[sharetest]
	path = /mnt/sda
	force user = root
	force group = root
	create mask = 0666
	directory mask = 0777
	guest ok = yes
```

**Comment by namjaejeon** [comment]
Ah.. I have checked writing file success(write word in txt file) with both clients(windows 10 and kernel cifs client). could you please explain more ? e.g. which kinds of file do you write or create ? or window or linux client ?...

**Comment by namjaejeon** [comment]
reproduced it. checking it now.

**Comment by namjaejeon** [comment]
Looks you are missing writeable = yes or read only = no. Could you please check again after adding writeable = yes ?

**Comment by namjaejeon** [comment]
[sharetest]
	path = /mnt/sda
	force user = root
	force group = root
	create mask = 0666
	directory mask = 0777
	guest ok = yes
        writeable = yes

**Comment by leonghui** [comment]
Adding `writeable = yes` worked.

**Comment by namjaejeon** [comment]
@leonghui Okay, Thanks!

**Comment by Andy2244** [comment]
ok my bad, actually had `option read_only 'no' ` in the example config, seems my late night copy&paste skills failed me.

Sorry should have found this mistake myself.

**Comment by kfur** [comment]
but for `smbd` write is work with `option read_only 'no'`.
