### ISSUE TITLE
cifsd & kcifsd version check

### ISSUE THREAD

**Issue by namjaejeon** [cifsd-team/cifsd#150]
cifsd and kcifsd should check each other's version. If kcifsd version is low and not mismatch with cifsd, cifsd should not be running. Because if there is some change for both kcifsd and cifsd, e.g. netlink related. cifsd may be crashed.
So the following are needed.
 1. increase minor version whenever release master branch.
 2. define kcifsd and cifsd version.
 3. add netlink request/response for version check. If version mismatch, cifsd should be not launched and show kcifsd and cifsd version info.
 4. show cifsd --help the corresponding version number of cifsd.

**Comment by sergey-senozhatsky** [comment]
On (07/14/19 01:27), Namjae Jeon wrote:
>    cifsd and kcifsd should check each other's version. If kcifsd version is
>    low and not mismatch with cifsd, cifsd should not be running. Because if
>    there is some change for both kcifsd and cifsd, e.g. netlink related.
>    cifsd may be crashed.
>    So the following are needed.
> 
>     1. increase minor version whenever release master branch.
>     2. define kcifsd and cifsd version.
>     3. add netlink request/response for version check. If version mismatch,
>        cifsd should be not launched and show kcifsd and cifsd version info.

No. We care only about those cases when cifsd-tools and kcifsd netlink
structures change their layout. No other internal change in cifsd-tools
or kcifsd can or should crash anything.

And in order to handle IPC layout changes we already have CIFSD_GENL_VERSION
in cifsd_server.h and in ipc code

	m->genlhdr->version != CIFSD_GENL_VERSION

	-ss

**Comment by sergey-senozhatsky** [comment]
So this is what happens when kcifsd and cifsd-tool were compiled against different
cifsd_server.h verions.

dmesg

[ 2114.977208] lt-cifsd/0 kcifsd: handle_startup_event:324: IPC protocol version mismatch: 1
[ 2115.981198] lt-cifsd/2 kcifsd: handle_startup_event:324: IPC protocol version mismatch: 1
[ 2116.985316] lt-cifsd/5 kcifsd: handle_startup_event:324: IPC protocol version mismatch: 1


cifsd-tools
[cifsd-worker/8686]: ERROR: Recv() error Invalid input data or parameter [-7]
[cifsd-manager/8672]: ERROR: WARNING: child process exited abnormally: 8686
[cifsd-worker/8687]: ERROR: Recv() error Invalid input data or parameter [-7]
[cifsd-manager/8672]: ERROR: WARNING: child process exited abnormally: 8687
[cifsd-worker/8690]: ERROR: Recv() error Invalid input data or parameter [-7]
[cifsd-manager/8672]: ERROR: WARNING: child process exited abnormally: 8690

-ss

**Comment by namjaejeon** [comment]
You only have known it, user don't know why this error happened. and no need to progress with this error when version is not mismatch. This is not user friendly. and Did you close this issue without any concent of REPORTER ?

**Comment by sergey-senozhatsky** [comment]
> You only have known it, user don't know why this error happened. and no need to progress with this error when version is not mismatch. This is not user friendly. 

The error message says "Version mismatch" - how is that not user friendly?

This "error" should never happen, really. The only reason we have CIFSD_GENL_VERSION is because
we have two cifsd_server.h files at the moment, but we always must have just one - once kcifsd is in the
mainline linux kernel, cifsd_server.h copy which we keep in cifsd-tools will be removed, and the one and
only cifsd_server.h will be installed with the rest of the kernel headers to /usr/include/linux, which makes
it **impossible** to compile cifsd-tools and kcifsd using different cifsd_server.h file.

-ss

**Comment by namjaejeon** [comment]
> The error message says "Version mismatch" - how is that not user friendly?
Ah, User don't know what they do. update kcifs ? or update cifsd ? they don't know which daemon should be updated. We are always building both packages(kicfsd, cifsd), but user could build only one.
> besides, what users are we talking about?
normal users, they can be not developer or newbie. You are thinking cifsd should be used by senior developer?

> Those are maintainers of cifsd-tools and kcifsd in given distribution - people who pull the code and
 compile it - who can see the "version mismatch" error during testing. And they are capable to resolve
 such an error. This "error" is not expected to happen. The reason we have CIFSD_GENL_VERSION is because  we have two cifsd_server.h files at the moment, but we always must have just one - once kcifsd is  in the mainline linux kernel, cifsd_server.h copy which we keep in cifsd-tools will be removed, and
 the one and only cifsd_server.h will be installed with the rest of the kernel headers to /usr/include/linux,
 which makes it impossible to compile cifsd-tools and kcifsd using different 

User should update both cifsd and cifsd-tools ? why ? if they want to upgrade only one ? or want to upgrade least version upgrade, which version do they use ? what version is matching with cifsd-tools ?

> Umm, yes. The bug report says "implement version check". We already have it implemented. I think I have enough reasons to close it. If now the bug is that we need to change error messages a bit, then it's another thing and we can update report and re-open it.

I have never closed ISSUE without any concent. If reporter is not response for long time and I think it is not issue, only closed it.

And why not stop error message since first version mismatch error ? error prints is not only one in your message. i.e. errors are going on. and cifsd guide something to upgrade kcifsd or cifsd ? just print errors.

> And we probably can remove cifsd-tools cifsd_server.h right now and update kcifsd install script so it will always install cifsd_server.h to /usr/include/linux when we compile the module. So rebuild of cifsd-tools will always pick up the up-to-date kcifsd cifsd_server.h file.

It means user can not build cifsd-tools without kcifsd source ? more user unfrienly way.

**Comment by sergey-senozhatsky** [comment]
> > The error message says "Version mismatch" - how is that not user friendly?
> 
> Ah, User don't know what they do. update kcifs ? or update cifsd ? they don't know which daemon should be updated. We are always building both packages(kicfsd, cifsd), but user could build only one.

This is all handled by the distro. When you do apt-get upgrade/update you update all the packages
which it tells you to update, right?

> > besides, what users are we talking about?
> 
> normal users, they can be not developer or newbie. You are thinking cifsd should be used by senior developer?

Users use installed programs. Programs are compiled and tested by distro people.

> User should update both cifsd and cifsd-tools ? why ? if they want to upgrade only one ? or want to upgrade least version upgrade, which version do they use ? what version is matching with cifsd-tools ?
> 

There are no such "users"; and I would be pretty surprised to find distros which will let
anyone install a new kernel package without updating user-space apps which depend
on particular kernel version.

"users" do

```
opkg install cifsd cifsd-tools

and

opkg update
```

Not every kcifsd update requires cifsd-tools update; this is what reposible distro people
figure out and then either push new packge version, so people can update, or don't.

> And why not stop error message since first version mismatch error ? error prints is not only one in your message. i.e. errors are going on. and cifsd guide something to upgrade kcifsd or cifsd ? just print errors.
> 

The error messages and error handling can be improved.


> > And we probably can remove cifsd-tools cifsd_server.h right now and update kcifsd install script so it will always install cifsd_server.h to /usr/include/linux when we compile the module. So rebuild of cifsd-tools will always pick up the up-to-date kcifsd cifsd_server.h file.
> 
> It means user can not build cifsd-tools without kcifsd source ? more user unfrienly way.

This not less user firendly, this the way it's supposed to be. This is exactly the reasons why
you install kernel-headers package to compiler certain programs. Try to compile user-space
glibc or util-linux without installed kernel headers, for instance.

glibc configure.ac

```

AC_TRY_COMPILE([#include <linux/version.h>
#if !defined LINUX_VERSION_CODE || LINUX_VERSION_CODE < ]dnl
patsubst(LIBC_LINUX_VERSION,[^\([^.]*\)\.\([^.]*\)\.\([^.]*\)$],dnl
[ (\1 *65536+ \2 *256+ \3) /* \1.\2.\3 */])[
# error kernel headers missing or too old
#endif], [],
               [libc_cv_linuxVER='LIBC_LINUX_VERSION or later'],
               [libc_cv_linuxVER='missing or too old!'])])
if test "$libc_cv_linuxVER" != 'LIBC_LINUX_VERSION or later'; then
  AC_MSG_ERROR([GNU libc requires kernel header files from
Linux LIBC_LINUX_VERSION or later to be installed before configuring.
The kernel header files are found usually in /usr/include/asm and
/usr/include/linux; make sure these directories use files from
Linux LIBC_LINUX_VERSION or later.  This check uses <linux/version.h>, so
make sure that file was built correctly when installing the kernel header
files.  To use kernel headers not from /usr/include/linux, use the
configure option --with-headers.])
fi

```

or util-linux configure.ac

```
AS_IF([test "x$with_btrfs" != xno], [
  AS_CASE([$with_btrfs:$have_linux_btrfs_h],
    [yes:no],
    [AC_MSG_ERROR([btrfs selected but linux/btrfs.h not found])],
    [check:no],
       [AC_MSG_WARN([linux/btrfs.h not found, do not build with btrfs support])],


```
and
```
AC_CHECK_HEADERS([ \
        linux/btrfs.h \
        linux/cdrom.h \
        linux/falloc.h \
        linux/watchdog.h \
        linux/fd.h \
        linux/raw.h \
        linux/tiocl.h \
        linux/version.h \
        linux/securebits.h \
        linux/net_namespace.h \

```
User space tools don't carry around copies of kernel header files.

-ss

**Comment by namjaejeon** [comment]
> This is all handled by the distro. When you do apt-get upgrade/update you update all the packages
which it tells you to update, right?

cifsd package doesn't kcifsd mod, it contain cifsd and cifsadmin. So there is a possiblity to make mismatch.

> opkg install cifsd cifsd-tools

cifsd is kernel module. So user can install kernel package and cifsd-tools package. and we don't think that user use only package, user can manually build kcifsd and cifsd-tools source. We are currently guiding how to build in our github.

> The error messages and error handling can be improved.

Okay, How will you improve it ? just print version mismatch and stop print ? If user cifsd print needed or matched kcifsd version, user can know what they do. i.e. downgrade user cifsd or upgrade kcifsd.

> This is not less user firendly, this is the way things are supposed to be. This is exactly the reasons why
you install kernel-headers package to compiler certain programs. Try to compile user-space
glibc or util-linux without installed kernel headers, for instance.

okay, good idea. but it break only build time of cifsd-tools when kcifsd is installed first. If user reverse sequence, i.e. cifsd-tools build is first, and kcifsd build is next, it can not miss corrent version check.
Moreover, can not check version incase  of package install.

I am saying one more protection and give information to make user aware what is missing.

**Comment by Andy2244** [comment]
>     1. increase minor version whenever release master branch

Just as a example the current master branch has Cifsd: 2.0.3 Kmod: 2.0.4

**Comment by namjaejeon** [comment]
> Just as a example the current master branch has Cifsd: 2.0.3 Kmod: 2.0.4

There is no change in cifsd-tools. And we can't increment both ones at the same time if we consider kcifsd mod merged into linux mainline.

**Comment by Andy2244** [comment]
Sure, my point was i have no idea if those two different version work together or not. Would cifsd check this already and refuse to start with a 2.0 kmod + error message?

**Comment by sergey-senozhatsky** [comment]
On (19/12/10 05:21), Andy Walsh wrote:
>    Sure, my point was i have no idea if those two different version work
>    together or not. Would cifsd check this already and refuse to start with a
>    2.0 kmod + error message?

The thing that matters here is "IPC protocol version". When we change physical
layout (including sizeof()) of structures that cifsd-tools and kcifsd use for
IPC communication then we must update both user-space and kernel space cifsd,
otherwise bad things can happen. We check IPC protocol version mismatch.
// it's in cifsd_server header file //

Other than that cifsd-tools and kcifsd are totally independent. If we fix,
let's say, a memory leak in kcifsd and bump kcifsd minor version, it does not
affect cifsd-tools in any way. Thus we don't match "program versions". So
cifsd-tools 2.0.3 can work perfectly fine with kcifsd 2.0.10 (unless we
changed IPC structures).

	-ss
