### ISSUE TITLE
hangs on explorer on share right click

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd#152]
Just noticed that Win10 explorer will hang again, if i try to right-click on a share to pin it to the quicklist.
The share works if i just left click into it, i can see the contents.

```
[global]
	netbios name = router
	server string = Cifsd on OpenWrt
	workgroup = WORKGROUP
	interfaces = br-lan 
	bind interfaces only = yes
	ipc timeout = 8
	deadtime = 15
	map to guest = Bad User

[sharetest]
	path = /tmp/etc
	force user = root
	force group = root
	create mask = 0666
	directory mask = 0777
	guest ok = yes
```

Steps to reproduce:
1: In explorer type the hostname, for me `\\router`
2: The share should appear, now if i try right click the share explorer process hangs and needs to-be killed/restarted.

PS: I see no system/kernel log errors, warnings for cifsd.

**Comment by Andy2244** [comment]
ok if i add `writeable = yes` than it does not hang?
In read-only mode should be able to right-click without the explorer to hang.

**Comment by namjaejeon** [comment]
Hm.. I could not reproduce it with writeable or without writeable on my setup. (cifsd in fedora & windows 10)
 I will try more tommorow.

**Comment by namjaejeon** [comment]
I can not reproduce this issue.. Could you please reproduce with the latest master branch ?
Thanks!

**Comment by Andy2244** [comment]
Still happening for me with latest build from master, i can access/enter the share, but right click on the share icon hangs the explorer and i need to kill the process and manually restart explorer.

**Comment by sergey-senozhatsky** [comment]
On (07/21/19 05:30), Andy Walsh wrote:
>    Still happening for me with latest build from master, i can access/enter
>    the share, but right click on the share icon hangs the explorer and i need
>    to kill the process and manually restart explorer.

Is there anything unusual about your setup? Locale, smb.conf, etc.
Are you still able to simultaneously enum-shares from a linux client?
Hate to ask you, but maybe wireshark dump will shed some light on this.

	-ss

**Comment by namjaejeon** [comment]
@And2244 Could you provide wireshark dump ? It is helpful to resolve this issue. Indeed, I and sergey can not reproduce it on our targets.

**Comment by Andy2244** [comment]
Sure will try to grab some in the next days, if i have time.

**Comment by Andy2244** [comment]
Works from a fresh Win10 VM or via VPN from my work PC.
