### ISSUE TITLE
Not compiling with kernel 4.9

### ISSUE THREAD

**Issue by neheb** [cifsd-team/cifsd#156]
https://downloads.openwrt.org/snapshots/faillogs/armeb_xscale/packages/cifsd/compile.txt

**Comment by namjaejeon** [comment]
FIXED. please check the latest cifsd master.
Thanks for your report!!

**Comment by namjaejeon** [comment]
Oops, Sorry, I push the patch to master from cifsd-next now. please check it now.

**Comment by neheb** [comment]
Fixed
