### ISSUE TITLE
Is SMB1 supported ?

### ISSUE THREAD

**Issue by kofec** [cifsd-team/cifsd#176]
I tried to mount the resource via:

`sudo mount -t cifs //192.168.1.4/dysk3TB /tmp/NSA310 -o vers=1.0,user=root`

and on server side received:

```
Tue Jul 30 09:35:25 2019 user.notice cifsd: Starting CIFS/SMB userspace service.
Tue Jul 30 09:35:36 2019 kern.err kernel: [131299.457541] kcifsd: smb_handle_negotiate:450: Unsupported SMB protocol
```

**Comment by sergey-senozhatsky** [comment]
On (07/30/19 00:41), kofec wrote:
>    I tried to mount the resource via:
> 
>    sudo mount -t cifs //192.168.1.4/dysk3TB /tmp/NSA310Grawerska -o
>    vers=1.0,user=root
> 

Could you try vers=2.0? You probably don't have SMB1 enabled (which is
good).

	-ss

**Comment by kofec** [comment]
When I change to "2.0"
o client side I have: 
```
sudo mount -t cifs //192.168.1.4/dysk3TB /tmp/NSA310 -o vers=2.0,user=root
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
On server side:
`Tue Jul 30 10:01:27 2019 kern.err kernel: [132850.050972] kcifsd: smb2_handle_negotiate:927: Server dialect :0xffff not supported`

When I change to "2.1"
All is fine

**Comment by sergey-senozhatsky** [comment]
On (07/30/19 01:04), kofec wrote:
> 
>    When I change to "2.1"
>    All is fine

Sorry, yes, that makes sense. Insecure protocols are smb1 and smb2.0

Do you see any I/O speed changes after you switch to smb2.1?

	-ss

**Comment by kofec** [comment]
I'm not sure what do you mean I/O speed but transfer is the same (14MB/s).
As I understand I achieve the same by "server max protocol = SMB2" ?
How can I enable insecure protocols ? Maybe ciphering takes a lot of resources and that slow down the transfer?

**Comment by sergey-senozhatsky** [comment]
> _"You probably don't have SMB1 enabled"_ - you mean on server or client side ?

Server side (well, both). If cifsd was compiled without CONFIG_CIFS_INSECURE_SERVER
support then only SMB2.1 and higher dialect versions are supported.

Linux CIFS client has a similar CONFIG_CIFS_ALLOW_INSECURE_LEGACY option:

```
Modern dialects, SMB2.1 and later (including SMB3 and 3.1.1), have additional
security features, including protection against man-in-the-middle attacks and stronger
crypto hashes, so the use of legacy dialects (SMB1/CIFS and SMB2.0) is discouraged. 
```

The trend these days is to finally disabled SMB1 and SMB2.0

-ss

**Comment by kofec** [comment]
Thanks for the answers -  so I close the issue
