### ISSUE TITLE
No working shares with latest version?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd#185]
Not getting any shares with latest git version? Service starts-up fine, no errors, module is loaded and all looks fine? Explorer wont list the share via` \\router` and i cant enter it via PS `cd \\router\sharetest`

```
[global]
	netbios name = router
	server string = Cifsd on OpenWrt
	workgroup = WORKGROUP
	interfaces = br-lan 
	bind interfaces only = yes
	ipc timeout = 8
	deadtime = 15
	map to guest = Bad User

[sharetest]
	path = /tmp/etc
	force user = root
	force group = root
	create mask = 0666
	directory mask = 0777
	writeable = yes
	guest ok = yes
```

**Comment by namjaejeon** [comment]
hm.. When I try it, it work fine.., Could you please share wireshark dump ?

**Comment by Andy2244** [comment]
Will look into this on the weekend, not getting any shares is weird.

**Comment by Andy2244** [comment]
Seem to-be some odd bug on my PC at home, mounting via a linux VM or VPN from my work PC works. So no idea how i broke it on my home PC.
