### ISSUE TITLE
compile error on mips (vfree vs kvfree)

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd#186]
Seem's for mips you need to use kvfree/kvmalloc in vfs.c/vfs_cache.c.

```
make[3]: Entering directory '/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.19.57'
  CC [M]  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.o
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c: In function 'cifsd_vfs_inherit_smack':
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c:128:3: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
   vfree(xattr_list);
   ^~~~~
   kvfree
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c: In function 'cifsd_vfs_listxattr':
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c:1268:10: error: implicit declaration of function 'vmalloc'; did you mean 'kvmalloc'?  -Werror=implicit-function-declaration]
  vlist = vmalloc(size);
          ^~~~~~~
          kvmalloc
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c:1268:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  vlist = vmalloc(size);
        ^
```

```
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs_cache.c: In function 'cifsd_inode_hash_init':
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs_cache.c:233:20: error: implicit declaration of function '__vmalloc'; did you mean '__kmalloc'? [-Werror=implicit-function-declaration]
  inode_hashtable = __vmalloc(size, GFP_ATOMIC, PAGE_KERNEL);
                    ^~~~~~~~~
                    __kmalloc
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs_cache.c:233:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  inode_hashtable = __vmalloc(size, GFP_ATOMIC, PAGE_KERNEL);
                  ^
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs_cache.c: In function 'cifsd_release_inode_hash':
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs_cache.c:244:2: error: implicit declaration of function 'vfree'; did you mean 'kvfree'?  -Werror=implicit-function-declaration]
  vfree(inode_hashtable);
  ^~~~~
  kvfree
```

**Comment by sergey-senozhatsky** [comment]
On (08/08/19 02:39), Andy Walsh wrote:
>    Seem's for mips you need to use kvfree/kvmalloc.
> 
>  make[3]: Entering directory '/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.19.57'
>    CC [M]  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.o
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c: In function 'cifsd_vfs_inherit_smack':
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c:128:3: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
>     vfree(xattr_list);
>     ^~~~~
>     kvfree
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c: In function 'cifsd_vfs_listxattr':
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c:1268:10: error: implicit declaration of function 'vmalloc'; did you mean 'kvmalloc'?  -Werror=implicit-function-declaration]
>    vlist = vmalloc(size);
>            ^~~~~~~
>            kvmalloc
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-05-faef9237/vfs.c:1268:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
>    vlist = vmalloc(size);
>          ^

I'd rather switch to our helpers. cifsd_alloc/cifsd_free.

===

Subject: [PATCH] cifsd: switch vfs to buffer_pool API

Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
---
 vfs.c | 22 +++++++++++-----------
 1 file changed, 11 insertions(+), 11 deletions(-)

diff --git a/vfs.c b/vfs.c
index f0321ed..addab47 100644
--- a/vfs.c
+++ b/vfs.c
@@ -125,7 +125,7 @@ static void cifsd_vfs_inherit_smack(struct cifsd_work *work,
 	}
 
 	if (xattr_list)
-		vfree(xattr_list);
+		cifsd_free(xattr_list);
 }
 
 /**
@@ -235,7 +235,7 @@ static ssize_t cifsd_vfs_getcasexattr(struct dentry *dentry,
 
 out:
 	if (xattr_list)
-		vfree(xattr_list);
+		cifsd_free(xattr_list);
 	return value_len;
 }
 
@@ -824,7 +824,7 @@ int cifsd_vfs_readdir_name(struct cifsd_work *work,
 	dir_pathlen = strlen(dir_path);
 	/* 1 for '/'*/
 	file_pathlen = dir_pathlen +  de_name_len + 1;
-	name = kmalloc(file_pathlen + 1, GFP_KERNEL);
+	name = cifsd_alloc(file_pathlen + 1, GFP_KERNEL);
 	if (!name)
 		return -ENOMEM;
 
@@ -836,7 +836,7 @@ int cifsd_vfs_readdir_name(struct cifsd_work *work,
 	rc = cifsd_vfs_kern_path(name, LOOKUP_FOLLOW, &path, 1);
 	if (rc) {
 		cifsd_err("lookup failed: %s [%d]\n", name, rc);
-		kfree(name);
+		cifsd_free(name);
 		return -ENOMEM;
 	}
 
@@ -844,7 +844,7 @@ int cifsd_vfs_readdir_name(struct cifsd_work *work,
 	fill_create_time(work, &path, cifsd_kstat);
 	fill_file_attributes(work, &path, cifsd_kstat);
 	path_put(&path);
-	kfree(name);
+	cifsd_free(name);
 	return 0;
 }
 #else
@@ -1265,7 +1265,7 @@ ssize_t cifsd_vfs_listxattr(struct dentry *dentry, char **list)
 	if (size <= 0)
 		return size;
 
-	vlist = vmalloc(size);
+	vlist = cifsd_alloc(size);
 	if (!vlist)
 		return -ENOMEM;
 
@@ -1307,7 +1307,7 @@ ssize_t cifsd_vfs_getxattr(struct dentry *dentry,
 	if (xattr_len < 0)
 		return xattr_len;
 
-	buf = kmalloc(xattr_len + 1, GFP_KERNEL);
+	buf = cifsd_alloc(xattr_len + 1, GFP_KERNEL);
 	if (!buf)
 		return -ENOMEM;
 
@@ -1410,7 +1410,7 @@ int cifsd_vfs_truncate_xattr(struct dentry *dentry, int wo_streams)
 	}
 out:
 	if (xattr_list)
-		vfree(xattr_list);
+		cifsd_free(xattr_list);
 
 	return err;
 }
@@ -1538,7 +1538,7 @@ int cifsd_vfs_fiemap(struct cifsd_file *fp, u64 start, u64 length,
 		*out_start = fieinfo.fi_extents_start->fe_logical;
 		*out_length = fieinfo.fi_extents_start->fe_length;
 	}
-	kfree(fieinfo.fi_extents_start);
+	cifsd_free(fieinfo.fi_extents_start);
 	return ret;
 }
 
@@ -1904,7 +1904,7 @@ ssize_t cifsd_vfs_casexattr_len(struct dentry *dentry,
 
 out:
 	if (xattr_list)
-		vfree(xattr_list);
+		cifsd_free(xattr_list);
 	return value_len;
 }
 
@@ -1917,7 +1917,7 @@ int cifsd_vfs_xattr_stream_name(char *stream_name,
 
 	stream_name_size = strlen(stream_name);
 	xattr_stream_name_size = stream_name_size + XATTR_NAME_STREAM_LEN + 1;
-	xattr_stream_name_buf = kmalloc(xattr_stream_name_size, GFP_KERNEL);
+	xattr_stream_name_buf = cifsd_alloc(xattr_stream_name_size, GFP_KERNEL);
 
 	memcpy(xattr_stream_name_buf,
 		XATTR_NAME_STREAM,
-- 
2.22.0

**Comment by Andy2244** [comment]
As noted same problem in vfs_cache.c

**Comment by sergey-senozhatsky** [comment]
On (08/09/19 00:39), Andy Walsh wrote:
>    As noted same problem in vfs_cache.c

Hi Andy,
I'm traveling right now. Will take a look a bit later. Thanks!

	-ss

**Comment by sergey-senozhatsky** [comment]
JFI, sent out a vfs_cache patch.

-ss

**Comment by Andy2244** [comment]
thanks, compiles with latest master

**Comment by Andy2244** [comment]
vfs.c still uses vfree/vmalloc and fails on mips, is this a oversight and can i patch those last instances with cifsd_free/alloc?

```
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c: In function 'cifsd_vfs_inherit_smack':
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c:128:3: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
   vfree(xattr_list);
   ^~~~~
   kvfree
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c: In function 'cifsd_vfs_listxattr':
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c:1260:10: error: implicit declaration of function 'vmalloc'; did you mean 'kvmalloc'?  -Werror=implicit-function-declaration]
  vlist = vmalloc(size);
          ^~~~~~~
          kvmalloc
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c:1260:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  vlist = vmalloc(size);
        ^
cc1: some warnings being treated as errors

```

**Comment by sergey-senozhatsky** [comment]
On (08/21/19 02:34), Andy Walsh wrote:
>    vfs.c still uses vfree/vmalloc and fails on mips, is this a oversight and
>    can i patch those last instances with cifsd_free/alloc?
> 
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c: In function 'cifsd_vfs_inherit_smack':
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c:128:3: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
>     vfree(xattr_list);
>     ^~~~~
>     kvfree
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c: In function 'cifsd_vfs_listxattr':
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c:1260:10: error: implicit declaration of function 'vmalloc'; did you mean 'kvmalloc'?  -Werror=implicit-function-declaration]
>    vlist = vmalloc(size);
>            ^~~~~~~
>            kvmalloc
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/vfs.c:1260:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
>    vlist = vmalloc(size);

Hi Andy,

I dropped the old pull request, those 2 trivial patches have never
made it to any branches. The pull request was in pending state for
entirely too long and even gained merge conflicts (was way too much
effort at that point). There is a new pull request now. Maybe will
get merged at last, who knows.

The 3 patches, you might be interested in, are:

https://github.com/cifsd-team/cifsd/pull/199/commits/82455b0edc2f086e1cba3ca42e3edd3ec46dd410
https://github.com/cifsd-team/cifsd/pull/199/commits/0c9f682986e171a0d74fd3430dd2f65f24d14553
https://github.com/cifsd-team/cifsd/pull/199/commits/f632adeb7e1fe99b9e255f770f139253a5f4562c

	-ss

**Comment by Andy2244** [comment]
ok those work for vfs.c/cache.c, than smb2pdu.c fails.

```
smb2pdu.c: In function 'smb2_get_ea':
/root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/smb2pdu.c:3710:3: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
   vfree(xattr_list);
   ^~~~~
   kvfree
cc1: some warnings being treated as errors
```

**Comment by sergey-senozhatsky** [comment]
On (08/21/19 03:40), Andy Walsh wrote:
>    ok those work for vfs.c/cache.c, than smb2pdu.c fails.
> 
>  smb2pdu.c: In function 'smb2_get_ea':
>  /root/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/cifsd-2019-08-19-b919acf3/smb2pdu.c:3710:3: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
>     vfree(xattr_list);
>     ^~~~~
>     kvfree

Nasty!

Thanks for the report. That thing, BTW, does not look right.
The following patch should improve it.

===

SMB1/SMB2 don't know exactly how vfs layer allocates xattr list,
via kmalloc() or vmalloc(). Introduce cifsd_vfs_xattr_free() and
keep both xattr allocation and de-allocation in one place.

Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
---
 smb1pdu.c | 4 ++--
 smb2pdu.c | 6 ++----
 vfs.c     | 6 ++++++
 vfs.h     | 1 +
 4 files changed, 11 insertions(+), 6 deletions(-)

diff --git a/smb1pdu.c b/smb1pdu.c
index 35599ef..8cb92cf 100644
--- a/smb1pdu.c
+++ b/smb1pdu.c
@@ -8,6 +8,7 @@
 #include <linux/posix_acl_xattr.h>
 #include <linux/namei.h>
 #include <linux/statfs.h>
+#include <linux/vmalloc.h>
 
 #include "glob.h"
 #include "smb1pdu.h"
@@ -3844,8 +3845,7 @@ done:
 	rsp->ByteCount = cpu_to_le16(rsp_data_cnt + 5);
 	inc_rfc1001_len(&rsp->hdr, (10 * 2 + rsp->ByteCount));
 out:
-	if (xattr_list)
-		vfree(xattr_list);
+	cifsd_vfs_xattr_free(xattr_list);
 	return rc;
 }
 
diff --git a/smb2pdu.c b/smb2pdu.c
index 754258f..2727622 100644
--- a/smb2pdu.c
+++ b/smb2pdu.c
@@ -3867,8 +3867,7 @@ done:
 	rsp->OutputBufferLength = cpu_to_le32(rsp_data_cnt);
 	inc_rfc1001_len(rsp_org, rsp_data_cnt);
 out:
-	if (xattr_list)
-		vfree(xattr_list);
+	cifsd_vfs_xattr_free(xattr_list);
 	return rc;
 }
 
@@ -4151,8 +4150,7 @@ static void get_file_stream_info(struct cifsd_work *work,
 	/* last entry offset should be 0 */
 	file_info->NextEntryOffset = 0;
 out:
-	if (xattr_list)
-		vfree(xattr_list);
+	cifsd_vfs_xattr_free(xattr_list);
 
 	rsp->OutputBufferLength = cpu_to_le32(nbytes);
 	inc_rfc1001_len(rsp_org, nbytes);
diff --git a/vfs.c b/vfs.c
index 556b1a5..6da6f8e 100644
--- a/vfs.c
+++ b/vfs.c
@@ -1550,6 +1550,12 @@ int cifsd_vfs_remove_xattr(struct dentry *dentry, char *attr_name)
 	return vfs_removexattr(dentry, attr_name);
 }
 
+void cifsd_vfs_xattr_free(char *xattr)
+{
+	if (xattr)
+		vfree(xattr);
+}
+
 int cifsd_vfs_unlink(struct dentry *dir, struct dentry *dentry)
 {
 	int err = 0;
diff --git a/vfs.h b/vfs.h
index ee54daf..16b4f9e 100644
--- a/vfs.h
+++ b/vfs.h
@@ -186,6 +186,7 @@ int cifsd_vfs_xattr_stream_name(char *stream_name,
 
 int cifsd_vfs_truncate_xattr(struct dentry *dentry, int wo_streams);
 int cifsd_vfs_remove_xattr(struct dentry *dentry, char *attr_name);
+void cifsd_vfs_xattr_free(char *xattr);
 
 int cifsd_vfs_kern_path(char *name, unsigned int flags, struct path *path,
 		bool caseless);
-- 
2.23.0

**Comment by Andy2244** [comment]
ok compiles now, the smb1pdu.c/smb2pdu.c patch seems based on your local version not master, patch needs lots of offsets.

**Comment by sergey-senozhatsky** [comment]
On (08/21/19 04:32), Andy Walsh wrote:
>    ok compiles now, the smb1pdu.c/smb2pdu.c patch seems based on your local
>    version not master, patch needs lots of offsets.

Oh, my bad...
Against cifsd-next. I don't use master.

	-ss
