### ISSUE TITLE
Probably KSMBD_STARTUP_CONFIG_INTERFACES(req) returns wrong interface name

### ISSUE THREAD

**Issue by monsterzzzz** [cifsd-team/cifsd#347]
The first 4 chars are missing.
In the conf. file, the settings are:
[global]
	netbios name = |NAME|
	server string = |DESCRIPTION|
	workgroup = |WORKGROUP|
	interfaces = br-lan
	bind interfaces only = yes
	ipc timeout = 20
	deadtime = 15
	map to guest = Bad User
	smb2 max read = 64K
	smb2 max write = 64K
	smb2 max trans = 64K
	cache read buffers = no
	cache trans buffers = no

but in the log file, we got "Unknown interface: an"
br-lan---->an, first 4 chars are missing.

**Comment by namjaejeon** [comment]
I can't even reproduce it using your setting. Could you please debug more on your reproducible settings ?

**Comment by monsterzzzz** [comment]
Using the settings above we got "ksmbd: ksmbd_tcp_set_interfaces:596: Unknown interface: an". Obviously the "br-lan" was cut into "an". If I set "interfaces = AAAAbr-lan", it just works. Is it due to "share_fake_fscaps" was added? With the same conf. file on Version 3.1.3, everything works fine.

**Comment by namjaejeon** [comment]
Got it, You are using cifsd(ksmbd) version 3.1.4, right ? If so, what version of cifsd-tools are you using ? If you used 3.2.1, you should use 3.2.2 version to match with ksmbd(cifsd) 3.1.4.

**Comment by monsterzzzz** [comment]
> Got it, You are using cifsd(ksmbd) version 3.1.4, right ? If so, what version of cifsd-tools are you using ? If you used cifsd-tools 3.2.1 version, you should use 3.2.2 version to match with ksmbd(cifsd) 3.1.4.

Exactly! I will try cifsd-tools 3.2.2. Thank you!

**Comment by namjaejeon** [comment]
Good! Close this issue.
