### ISSUE TITLE
failed using infuse app on iOS/tvOS

### ISSUE THREAD

**Issue by sicaryo** [cifsd-team/cifsd#359]
Using infuse app (a media player on iOS and tvOS), could find the share but failed to connect. tried to specify the smb version to 2 and 3, or specify ip addrs,  not working. 

Infuse is widely used for fruit/appl users, it would be great if we can make Ksmbd work for them. thanks!

**Comment by namjaejeon** [comment]
Could you please check it with #ksmbd-next branch(https://github.com/cifsd-team/cifsd/tree/ksmbd-next) if you don't try it ?

git clone --branch=ksmbd-next https://github.com/cifsd-team/ksmbd

We did recently fix some issues with iphone app. This change is in #ksmbd-next branch.

**Comment by sicaryo** [comment]
tried the *-next branch, still no luck. switched on debuting, check the log behind. I compared it with successful connection by macOS. what I can see the difference is in the failed log there is no more action after checking the IPC$, rather than in the good log there is IPC path creation..


----log of failure---
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.468142] ksmbd: ksmbd_decode_ntlmssp_auth_blob:557: decode_ntlmssp_authenticate_blob dname
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.476759] ksmbd: generate_smb3signingkey:964: dumping generated AES signing keys
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.484390] ksmbd: generate_smb3signingkey:965: Session Id    2
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.490339] ksmbd: generate_smb3signingkey:966: Session Key   51 9b 32 39 e1 52 fd 40 1b ff ec 61 fd 6f aa 44
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.500315] ksmbd: generate_smb3signingkey:968: Signing Key   be 0a 8f c0 d7 f1 d8 d1 8b 67 4c 77 24 21 e3 b7
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.510300] ksmbd: smb2_set_rsp_credits:400: credits: requested[17] granted[17] total_granted[49]
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.521067] ksmbd: ksmbd_conn_handler_loop:314: RFC1002 header 102 bytes
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.527833] ksmbd: smb2_get_ksmbd_tcon:103: skip to check tree connect request
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.535107] ksmbd: ksmbd_verify_smb_message:151: got SMB2 command
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.541229] ksmbd: smb2_calc_size:248: SMB2 data length 30 offset 72
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.547621] ksmbd: smb2_calc_size:264: SMB2 len 102
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.552528] ksmbd: smb2_tree_connect:1559: tree connect request for tree IPC$ treename \\hp.local\IPC$
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.562014] ksmbd: smb2_tree_connect:1570: IPC share path request
Thu Mar 12 14:30:26 2020 kern.info kernel: [  860.568151] ksmbd: smb2_set_rsp_credits:400: credits: requested[1] granted[1] total_granted[49]

**Comment by namjaejeon** [comment]
Okay, Could you please share wireshark or tcpdump file to analyse SMB packets ?
If you provide dump file to two case(success with MacOS, and failure with infuse app), I can fix them.

**Comment by sicaryo** [comment]
attached tcpdump files, see if them a bit help. and thanks really!

[infuse.pcap.zip](https://github.com/cifsd-team/cifsd/files/4325090/infuse.pcap.zip)
[mac.pcap.zip](https://github.com/cifsd-team/cifsd/files/4325093/mac.pcap.zip)

**Comment by namjaejeon** [comment]
Sorry, Could you please share one more dump between infuse app and samba ? Because I need to check packets when infuse app succeed to connect with some server.

**Comment by sicaryo** [comment]
not at all. my pleasure to do some help.

this was dumped for infuse to samba4 and succeeded. file size was large, just check the beginning packets I guess..

[infuse_good.pcap.zip](https://github.com/cifsd-team/cifsd/files/4327234/infuse_good.pcap.zip)

**Comment by namjaejeon** [comment]
```
diff --git a/smb2pdu.c b/smb2pdu.c
index 0d1f9d3..117f205 100644
--- a/smb2pdu.c
+++ b/smb2pdu.c
@@ -7901,7 +7901,7 @@ int smb3_final_sess_setup_resp(struct ksmbd_work *work)
        struct ksmbd_conn *conn = work->conn;
        struct smb2_hdr *rsp = RESPONSE_BUF(work);
 
-       if (conn->dialect != SMB311_PROT_ID)
+       if (conn->dialect < SMB302_PROT_ID)
                return 0;
 
        if (work->next_smb2_rcv_hdr_off)
```
Can you check if it improves after applying the patch above?

**Comment by sicaryo** [comment]
still not working. seems this time got 26 packets more than before patched

[infuse2_bad.pcap.zip](https://github.com/cifsd-team/cifsd/files/4327702/infuse2_bad.pcap.zip)

**Comment by namjaejeon** [comment]
Thanks for your testing!
please revert previous patch. and
```
diff --git a/mgmt/ksmbd_ida.c b/mgmt/ksmbd_ida.c
index ff0873d..ca8164c 100644
--- a/mgmt/ksmbd_ida.c
+++ b/mgmt/ksmbd_ida.c
@@ -43,7 +43,7 @@ int ksmbd_acquire_smb2_tid(struct ksmbd_ida *ida)
        int id;
 
        do {
-               id = __acquire_id(ida, 0, 0);
+               id = __acquire_id(ida, 1, 0);
        } while (id == 0xFFFF);
 
        return id;
```
Please try this change.

**Comment by sicaryo** [comment]
no...  however more a line added in log.

---
Fri Mar 13 14:27:20 2020 kern.info kernel: [87073.482900] ksmbd: smb2_tree_connect:1559: tree connect request for tree IPC$ treename \\hp.local\IPC$
Fri Mar 13 14:27:20 2020 kern.info kernel: [87073.492636] ksmbd: smb2_tree_connect:1570: IPC share path request
Fri Mar 13 14:27:20 2020 kern.info kernel: [87073.498885] ksmbd: smb2_set_rsp_credits:400: credits: requested[1] granted[1] total_granted[49]

[infuse.pcap.zip](https://github.com/cifsd-team/cifsd/files/4328168/infuse.pcap.zip)

**Comment by namjaejeon** [comment]
Okay, I will buy iphone and directly check it. please wait a bit more.

**Comment by namjaejeon** [comment]
FIXED. Can you check the latest cifsd(ksmbd) master(tag 3.1.6) ?

**Comment by sicaryo** [comment]
NEAT! tested ok on infuse/tvOS. step closer to replace samba4, if... vfs/fruit/timemachine supported :)

Really Thanks!
