### ISSUE TITLE
Can I build this in Archlinux?

### ISSUE THREAD

**Issue by silenceleaf** [cifsd-team/cifsd#384]
make and I got this error

make -C /lib/modules/5.6.2-arch1-2/build M=/home/junyan/storage/src/cifsd modules
make[1]: *** /lib/modules/5.6.2-arch1-2/build: No such file or directory.  Stop.
make: *** [Makefile:37: all] Error 2

**Comment by hclee** [comment]
Hello @silenceleaf,
You might refer to "out-of-tree module compilation" at https://wiki.archlinux.org/index.php/Compile_kernel_module.
I have never used Archlinux (;

**Comment by namjaejeon** [comment]
@silenceleaf Can I close this ISSUE if you resolve it ?

**Comment by silenceleaf** [comment]
yes, I will close this.
