### ISSUE TITLE
SMB2_FIND_ID_BOTH_DIRECTORY_INFO return access denied

### ISSUE THREAD

**Issue by luizluca** [cifsd-team/cifsd#388]
Hello,

Since #334 closed, one of my apps changed from smb1 to smb2. It's now using SMB2_FIND_ID_BOTH_DIRECTORY_INFO instead of FIND_FIRST2

And now I have new issues:

```
47	0.274079	192.168.3.26	SMB2	192.168.3.1	168	Find Request File:  SMB2_FIND_ID_BOTH_DIRECTORY_INFO Pattern: *
48	0.281942	192.168.3.1	SMB2	192.168.3.26	143	Find Response, Error: STATUS_ACCESS_DENIED
```

And I get these dmesg:

```
[ 1220.529360] ksmbd: smb2_query_dir:3503: no right to enumerate directory (/)
[ 1220.560510] ksmbd: smb2_query_dir:3503: no right to enumerate directory (tftpboot)
[ 1221.245743] ksmbd: smb2_query_dir:3503: no right to enumerate directory (/)
```

As usual, samba36 works as expected.

```
42	0.182448	192.168.3.26	SMB2	192.168.3.1	168	Find Request File:  SMB2_FIND_ID_BOTH_DIRECTORY_INFO Pattern: *
44	0.186468	192.168.3.1	SMB2	192.168.3.26	740	Find Response
46	0.193784	192.168.3.26	SMB2	192.168.3.1	168	Find Request File:  SMB2_FIND_ID_BOTH_DIRECTORY_INFO Pattern: *
47	0.194508	192.168.3.1	SMB2	192.168.3.26	143	Find Response, Error: STATUS_NO_MORE_FILES
```

I tested with ksmbd-next from 2020-03-17-00-05-53 and 2020-04-19-00-04-37.

Is it another Endianess issue?
https://github.com/cifsd-team/cifsd/blob/92aad32029be51bbfd4897696e21371e7ce08d7a/smb2pdu.c#L3559

Target directory permission does not seem to matter.

**Comment by hclee** [comment]
Hello @luizluca,
We recently have added the feature that allows files to be accessed only for users who has access rights. So you have to check that the login user have access rights for the directory.

If you don't want this feature, you can add "force uid = root" parameter in smb.conf.

**Comment by hclee** [comment]
@luizluca, If there are not other problems, could you close this issue?

**Comment by luizluca** [comment]
> Hello @luizluca,
> We recently have added the feature that allows files to be accessed only for users who has access rights. So you have to check that the login user have access rights for the directory.

Sorry @hclee , I missed this comment.

All my directories since / are world readable:

 drwxr-xr-x   17 root     root          4096 Mar 30 11:16 .

It is not FS permission. And samba3 does work with the same conf.

> If you don't want this feature, you can add "force uid = root" parameter in smb.conf.

I did give a try and forcing root does not change the permission error. It might be something else, maybe big endian issue with permission check.

**Comment by namjaejeon** [comment]
@luizluca Can you confirm this issue happen with ksmbd 3.1.6 version ? Because Hyunchul's patch-set is merged into 3.1.7 version.

sh-3.2# cat /sys/module/ksmbd/version
3.1.7

**Comment by luizluca** [comment]
> @luizluca Can you confirm this issue happen with ksmbd 3.1.6 version ? Because Hyunchul's patch-set is merged into 3.1.7 version.
> 
> sh-3.2# cat /sys/module/ksmbd/version
> 3.1.7

```
root@router.lan3:/# cat /sys/module/ksmbd/version
3.1.
```

If it is really needed, I can give another try with an older snapshot, but I will take some time as I only have 3.1.3 from distribution and my buildbot tracks git ksmbd-next.

**Comment by namjaejeon** [comment]
@luizluca okay, it is needed. I will wait.

**Comment by luizluca** [comment]
Update: Still happens on recent snapshot:

```
# cat /sys/module/ksmbd/version
3.1.9
```

The difference is that it does not show the "no right to enumerate directory" anymore. I didn't sniffed the traffic, but in the user perspective, it was the same.

As requested, I retried downgrading to 0d7ff8d7846d4825afeacdbeafc800982241d72c (module only). It was just the same (but now with the "no right to enumerate directory") back.

**Comment by Neustradamus** [comment]
@luizluca: Any news with latest code?

**Comment by luizluca** [comment]
I just tested current (2021-02-12-00-10-54) ksmbd-next and it is working perfectly now. Thanks!

```
# cat //sys/module/ksmbd/version
3.3.4
```
