### ISSUE TITLE
touch successfully updates timestamps of directories even in read-only filesystems

### ISSUE THREAD

**Issue by mrkiko** [cifsd-team/cifsd#391]
Hello!!

It seems touch is able to successfully update the timestamp of directories in a read only share on ksmbd.
Even the underneath filesystem is read only, still an
ls
on the server reflects updated timestamp.
My setup looks like:
client -> ksmbd server exporting read-only share -> ext4 read-only filesystem
the timestamp appears to be updated on the read only filesystem, even tough I am not sure this modification happens on the fsitself.

thanks for your great work!

Enrico

**Comment by hclee** [comment]
Hello @mrkiko,
I will check it. Thank you for this report.

**Comment by hclee** [comment]
This issue is fixed in #392. Could you test it?

**Comment by namjaejeon** [comment]
Pushed Hyunchul's pull request to #ksmbd-next branch.
@hclee Thanks for your work!
@mrkiko Could you please recheck it with #ksmbd-next branch ?

**Comment by mrkiko** [comment]
Thank you very very much! I can confirm this works as expected now!

After rebooting and remounting my disks, I can see timestamps are back to more expected values.
so, where did the system record my changes, eventough temporarily? Or was it my client caching them somehow?
closing this issue now. thanks again for your valuable work!
