### ISSUE TITLE
module doesn't shutdown completely upon removal

### ISSUE THREAD

**Issue by mrkiko** [cifsd-team/cifsd#394]
Hello!!

If this is a known issue, which I guess it is 99%, feel free to close this issue upfront.

[mrkiko@mStation tmp]$ mount # no ksmbd mounts on client laptop
/dev/sdb1 on / type ext4 (rw,noatime,nobarrier,noauto_da_alloc)
devtmpfs on /dev type devtmpfs (rw,relatime,size=8152980k,nr_inodes=2038245,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
efivarfs on /sys/firmware/efi/efivars type efivarfs (ro,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
tmpfs on /var/lib/dhcpcd type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1024k)
tmpfs on /var/lib/private/systemd type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1024k)
tmpfs on /var/log type tmpfs (rw,nosuid,nodev,noexec,relatime,size=20480k)
/dev/sda1 on /boot type vfat (ro,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
/dev/sda2 on /mnt/hdd type ext4 (rw,noatime,nobarrier,noauto_da_alloc)
devtmpfs on /var/lib/dhcpcd/dev type devtmpfs (rw,relatime,size=8152980k,nr_inodes=2038245,mode=755)
proc on /var/lib/dhcpcd/proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /var/lib/dhcpcd/sys type sysfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /var/lib/dhcpcd/run/udev type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /var/lib/dhcpcd/run/systemd/journal type tmpfs (rw,nosuid,nodev,mode=755)
/dev/sdc1 on /mnt/wd type ext4 (rw,noatime,nobarrier,noauto_da_alloc)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1631256k,mode=700,uid=1000,gid=1000)
[mrkiko@mStation tmp]$ ssh root@192.168.0.208 # connect to GnuBee PC 1 NAS where ksmbd runs

BusyBox v1.31.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r13046-df27e949fb
 -----------------------------------------------------
root@OpenWrt:~# lsmod |grep -i ksm # module not loaded anymore
root@OpenWrt:~# ps axw # still various kthreads related to ksmbd ?
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:02 /sbin/procd
    2 ?        S      0:00 [kthreadd]
    3 ?        I<     0:00 [rcu_gp]
    4 ?        I<     0:00 [rcu_par_gp]
    6 ?        I<     0:02 [kworker/0:0H-kblockd]
    8 ?        I<     0:00 [mm_percpu_wq]
    9 ?        S      2:46 [ksoftirqd/0]
   10 ?        I      0:39 [rcu_sched]
   11 ?        S      0:00 [migration/0]
   12 ?        S      0:00 [cpuhp/0]
   13 ?        S      0:00 [cpuhp/1]
   14 ?        S      0:00 [migration/1]
   15 ?        S      0:00 [ksoftirqd/1]
   17 ?        I<     0:03 [kworker/1:0H-kblockd]
   18 ?        S      0:00 [cpuhp/2]
   19 ?        S      0:00 [migration/2]
   20 ?        S      0:00 [ksoftirqd/2]
   22 ?        I<     0:01 [kworker/2:0H-kblockd]
   23 ?        S      0:00 [cpuhp/3]
   24 ?        S      0:00 [migration/3]
   25 ?        S      0:00 [ksoftirqd/3]
   27 ?        I<     0:01 [kworker/3:0H-kblockd]
   28 ?        I<     0:00 [netns]
  159 ?        S      0:00 [oom_reaper]
  160 ?        I<     0:00 [writeback]
  162 ?        S      0:01 [kcompactd0]
  171 ?        I<     0:00 [pencrypt_serial]
  173 ?        I<     0:00 [pdecrypt_serial]
  192 ?        I<     0:00 [kblockd]
  193 ?        I<     0:00 [blkcg_punt_bio]
  208 ?        S      0:00 [watchdogd]
  230 ?        S      6:04 [kswapd0]
  345 ?        S      0:02 [spi0]
  412 ?        I<     0:00 [ipv6_addrconf]
  413 ?        I<     0:00 [dsa_ordered]
  474 ?        S      0:00 [irq/27-keys]
  486 ?        I<     0:00 [ata_sff]
  498 ?        S      0:00 [scsi_eh_0]
  499 ?        I<     0:00 [scsi_tmf_0]
  503 ?        S      0:00 [scsi_eh_1]
  504 ?        I<     0:00 [scsi_tmf_1]
  515 ?        S      0:00 [scsi_eh_2]
  516 ?        I<     0:00 [scsi_tmf_2]
  519 ?        S      0:00 [scsi_eh_3]
  520 ?        I<     0:00 [scsi_tmf_3]
  532 ?        S      0:00 [scsi_eh_4]
  533 ?        I<     0:00 [scsi_tmf_4]
  536 ?        S      0:00 [scsi_eh_5]
  537 ?        I<     0:00 [scsi_tmf_5]
  632 ?        I<     0:00 [mmc_complete]
  798 ?        S      0:00 /sbin/ubusd
  799 ttyS0    Ss+    0:00 /sbin/askfirst /usr/libexec/login.sh
  816 ?        S      0:30 /sbin/urngd
 1027 ?        S      0:10 /sbin/logd -S 64
 1091 ?        S      0:00 /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.cfg01411c -k -x /var/run/dnsmasq/dnsmasq.cfg01411c.pid
 1131 ?        S      0:00 /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300 -T 3
 1171 ?        S      0:02 /sbin/netifd
 1396 ?        S<     0:00 /usr/sbin/ntpd -n -N -S /usr/sbin/ntpd-hotplug -p 0.openwrt.pool.ntp.org -p 1.openwrt.pool.ntp.org -p 2.o
 1727 ?        I<     0:00 [ext4-rsv-conver]
 1730 ?        I<     0:00 [ext4-rsv-conver]
 1732 ?        I<     0:00 [ext4-rsv-conver]
 1735 ?        I<     0:00 [ext4-rsv-conver]
 1737 ?        I<     0:00 [ext4-rsv-conver]
 1743 ?        I<     0:00 [ext4-rsv-conver]
 1910 ?        I<     0:00 [ext4-rsv-conver]
 2970 ?        I<     0:00 [kworker/1:2H-mmc_complete]
 2971 ?        I<     0:00 [kworker/0:1H-mmc_complete]
 2973 ?        I<     0:00 [kworker/3:2H-mmc_complete]
 2974 ?        I<     0:00 [kworker/2:1H-mmc_complete]
 3108 ?        I      0:00 [kworker/u8:1-events_unbound]
 5342 ?        I      0:00 [kworker/u8:2-events_unbound]
 5489 ?        I      0:00 [kworker/2:2-events]
 5573 ?        I      0:00 [kworker/2:0-events]
 5595 ?        Ss     0:01 /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300 -T 3
 5629 ?        I      0:00 [kworker/2:1-events]
 5717 ?        I      0:00 [kworker/1:4-mm_percpu_wq]
 5720 ?        I      0:00 [kworker/1:7-ksmbd-io]
 5727 ?        I      0:00 [kworker/0:7-events_power_efficient]
 5731 ?        I      0:00 [kworker/0:11-ksmbd-io]
 5765 ?        I      0:00 [kworker/3:19-events_power_efficient]
 5767 ?        I      0:00 [kworker/3:21-events]
 5834 ?        I      0:00 [kworker/u8:0-events_unbound]
 5945 ?        SN     0:00 [jffs2_gcd_mtd6]
 6058 ?        I      0:00 [kworker/2:3-events]
 6059 pts/0    Ss     0:00 -ash
 6069 pts/0    R+     0:00 ps axw
root@OpenWrt:~# umount /mnt/disk1
umount: can't unmount /mnt/disk1: Resource busy
root@OpenWrt:~# lsof -n |grep -i mnt
root@OpenWrt:~# lsof -n |grep -i disk1
root@OpenWrt:~# lsof -n |grep -i ksm
root@OpenWrt:~# Shared connection to 192.168.0.208 closed.
[mrkiko@mStation tmp]$ exit

**Comment by namjaejeon** [comment]
Sorry, I can not understand what issue you raise.
Have you tried to kill server like this ?

steps:
	- kill user space daemon
		killall ksmbd.mountd
	- kill kernel space daemon
		echo hard > /sys/class/ksmbd-control/kill_server

**Comment by mrkiko** [comment]
Hello!!
Thank you again for your work and follow-up. English isn't my native language, so forgive my tone if it's not what I wanted it to be.

So, the problem is - I am able to rmmod the module and still have ksmbd IO threads around, evne tough in the I scheduling state (don't know what it is).
The init.d script from the OpenWRt package kills the server, but I can't be 100% sure I invoked that.
Still, it should not be possible to rmmod the module and have it's code still running in the kernel I guess: and that's what the process list was meant to show, and lsmod call.
And I am sure about this, instead.
I guess it should be pretty easy to reproduce: just do some IO, then stop the server and rmmod the module, then lok for ksmbd-io threads.

**Comment by mrkiko** [comment]
I mean, look at PIDs 5720 and 5731, and module is not loaded.

And, disk1 can't be umounted even tough nothing appears to be holdingfiles on it, at least for what lsof says; admittedly, there could be other causes for this.

**Comment by namjaejeon** [comment]
Hi,
Thanks for your detailed explanation:)
I will try reproduce and fix it!

**Comment by namjaejeon** [comment]
And your english is not bad, I just want to get more information. :)

**Comment by hclee** [comment]
Hello @mrkiko,
Could you explain how to reproduce it in more detail? I cannot reproduce it.
Is the ksmbd version lastest?, and Is the kernel version 5.4?

**Comment by namjaejeon** [comment]
@hclee I didn't reproduce umount busy failure, but can see ksmbd-io kworker is still alive although ksmbd module is rmmoded.

I reproduced it like this.
               Server                                                              Client
     1. run ksmbd.mountd
                                                                         2. mount ksmbd's share
                                                                         3. dd if=/dev/zero of=test.bin bs=102400 count=1024
     4. killall ksmbd.mountd
     5. rmmod ksmbd (trying it till module unload)
     6. ps -ax (can see kworker-ksmbd-io)

I am wondering whether it is problem that ksmbd-io kworker is alive.

**Comment by mrkiko** [comment]
> Hello! Thank you again for your work and for those follow ups!
Yes, 5.4 kernel both on client and server, with latest ksmbd from next branch.
General workload is:
1: start ksmbd and mount share
2: let mpd (Music Player daemon) update its db
3: stop it at some point (or better, let it finish scanning all files)
4: try to shutdown ksmbd, and maybe check client dmesg

**Comment by namjaejeon** [comment]
Can not reproduce this issue...
