### ISSUE TITLE
3.1.9 release missing?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd#407]
Is there a reason 3.1.9 has no release yet?

**Comment by namjaejeon** [comment]
Ah, I forgot it because I was busy these days... I will do that today.
Thanks for letting me know it.

**Comment by namjaejeon** [comment]
ksmbd 3.1.9 and ksmbd-tools 3.2.5 version released.
Thanks!

**Comment by Andy2244** [comment]
cool thanks
