### ISSUE TITLE
Printers support

### ISSUE THREAD

**Issue by ahubchak** [cifsd-team/cifsd#41]
Hello all,

I was wandering, if there are any plans on implementing printers support, as it is mentioned in [MS-CIFS] that it is possible and SMB protocol supports printers.

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/934c2faa-54af-4526-ac74-6a24d126724e

Looking forward to your reply.

**Comment by namjaejeon** [comment]
Hi Andrew,
I don't have a plan now, So I do not even know how much work it is.
I can not afford to implement it because of many other more important works.
Thanks for your interest!
