### ISSUE TITLE
error/hang on viewing properties of share in Win10

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd#433]
I think we had this issue before, but seems back again.
If i try to right-click on the network share in windows explorer, the process just hangs and you need to kill the explorer.
In Total Commander you can get to the properties page, but that if you try access the `Network` or `Security` tab you get errors.

In the router i see those lines
```
__rpc_method:85: Unsupported RPC: lsarpc
ksmbd: create_smb2_pipe:1798: Unable to open RPC pipe: -22
```

PS: This is with latest 3.2.6 tools and 3.2.4 kmod.

**Comment by namjaejeon** [comment]
@Andy2244 Hi, I was working ACLs feature(#work.ACLs branch) these days, If it's implementation is completed, This issue will be fixed. And I didn't notice explorer hang issue on windows 10, I can just see  error and can't see permission in Security tab. Please wait a while.

**Comment by namjaejeon** [comment]
@Andy2244 Andy, I have released ksmbd/ksmbd-tools 3.3.0 version today. This version would fix this issue(by ACLs support).

**Comment by xdarklight** [comment]
@namjaejeon is there a hard-dependency on CONFIG_FS_POSIX_ACL now?

I just updated [0] the OpenWrt Makefile and now I am getting this at runtime:
```
[   69.697438] ksmbd: Unknown symbol posix_acl_alloc (err -2)
[   69.701977] ksmbd: Unknown symbol set_posix_acl (err -2)
[   69.708135] ksmbd: Unknown symbol get_acl (err -2)
```
and OpenWrt's `target/linux/generic/config-5.4` has:
```# CONFIG_FS_POSIX_ACL is not set```

also it's likely that I'm doing something wrong with the OpenWrt Makefile upgrade.
maybe @Andy2244 can help out

[0] https://gist.github.com/xdarklight/5cf4b6ea6fb941ae60a728f3de6a2bac

**Comment by namjaejeon** [comment]
@xdarklight Ouch! I missed checking it. I had to wrap these ones using #ifdef ~#endif. And I think that it is not problem to not use CONFIG_FS_POSIX_ACL in openWRT. It is just not able to modify permission of current file owner or add permission for new user. To avoid build break, I will fix it.

**Comment by namjaejeon** [comment]
@xdarklight Martin, I sent the patch for this issue. Could you please check the patch ?

**Comment by xdarklight** [comment]
the patch as mentioned by @namjaejeon: https://sourceforge.net/p/linux-cifsd/mailman/message/37164232/

another issue I am seeing (with above patch applied): #462

**Comment by namjaejeon** [comment]
I have released ksmbd/ksmbd-tools 3.3.1 version. Could you verify and pick it up ?

**Comment by Andy2244** [comment]
Kinda busy atm, will try to build/test it on the weekend, thanks.

**Comment by namjaejeon** [comment]
@Andy2244 Okay! Thanks!

**Comment by xdarklight** [comment]
@Andy2244 I (hope that I) made it a bit easier for you, see openwrt/packages#14127

**Comment by Andy2244** [comment]
Seems to work with 3.3.1, thanks.
