### ISSUE TITLE
Upstreaming plans

### ISSUE THREAD

**Issue by mrkiko** [cifsd-team/cifsd#448]
Hello!! I was curious to know if there where upstreaming plans for this project.
And, in such case, some ideas about how things where going on.

Thanks!

**Comment by namjaejeon** [comment]
Hello, We have a plan to upsteam ksmbd in linux mainline. Before that, I would like to know why you want to know a plan of ksmbd's upsteam first.

**Comment by mrkiko** [comment]
Hi!!

Oh - I was curious - I am following this project since some months now. I think it's a nice project.
I seen it perform very well. And was curious on future development! :)
Thanks for all the work and kindness!

**Comment by namjaejeon** [comment]
If our plan goes well, I expect ksmbd to merge into the linux mainline in the first half of next year. For more information, the version that smb1 is removed will be merged into linux mainline. If you want to know the shape of the mainline, please refer to the cifsd-for-next branch at https://github.com/smfrench/smb3-kernel. So I am going to support this cifsd-team/cifsd and cifsd in linux mainline simultaneously for those who need smb1.
