### ISSUE TITLE
Harmonization of commits

### ISSUE THREAD

**Issue by Neustradamus** [cifsd-team/cifsd#471]
There is a problem...

Currently in this repository, master branch, we can see:
- This branch is 16 commits ahead, 15 commits behind namjaejeon:master.

It is possible to have same code?

Thanks.

**Comment by namjaejeon** [comment]
Well, Do you check diff codes between this branch and namjaejeon:master ? The codes are not different.

**Comment by Neustradamus** [comment]
@namjaejeon: Maybe but it is source of problems, I am not alone to see this problem.
And it is not like this in other projects.

You can see an example here:
- https://github.com/SwikritiT/core (master of the fork, no problem of commits) and a branch: https://github.com/SwikritiT/core/tree/renameRecievedShare

If there are PRs, it must be merged before.

Please publish/merge all branches into upstream
Create a temporary repo in this organization
Transfer all issues into the temporary repo
Transfer the temporary repo near the upstream
Transfer all issues into the upstream
Remove the temporary repo
Remove this repo or move into another temporary place (not in your personal account)
Transfer the upstream here into this organization
If not removed, transfer the repo from temporary place to your github account
If remove before, create a new fork (better solution) to work

Do same for all repos.

**Comment by ptpt52** [comment]
@Neustradamus @namjaejeon 

just force push one of them and they would be the same commits.

```
git clone https://github.com/cifsd-team/cifsd.git
cd cifsd
git remote add upstream https://github.com/namjaejeon/cifsd.git
git fetch upstream
git diff upstream/master origin/master
git push --force upstream master

##now we force push from cifsd-team/cifsd/master --> namjaejeon.
```

**Comment by ptpt52** [comment]
if the namjaejeon/cifsd is the latest code
we should force push from namjaejeon/cifsd to cifsd-team
```
git clone https://github.com/cifsd-team/cifsd.git
cd cifsd
git remote add upstream https://github.com/namjaejeon/cifsd.git
git fetch upstream

git reset --hard HEAD~20
git pull --rebase upstream/master
git push --force origin master
```

**Comment by namjaejeon** [comment]
@ptpt52 Everything is well managed, so don't worry. Developers can check at the release and modification of cifsd in the cifsd-team.

**Comment by Neustradamus** [comment]
@namjaejeon: I am happy, I am not alone to see the difference and problem between personnal account vs organization.

@pali has confirmed the problem several months ago (pali commented on 12 Apr 2020):
- https://github.com/namjaejeon/exfatprogs/issues/18#issuecomment-612531558

@ptpt52 has confirmed the problem here too and specified you a little solution (ptpt52 commented on 3 Feb 2021):
- https://github.com/cifsd-team/cifsd/issues/471#issuecomment-772587252
- https://github.com/cifsd-team/cifsd/issues/471#issuecomment-772591033

All of us, I think try to help you to have perfect products...

Another solution is to detach organization repositories from personal account repositories:
- https://support.github.com/contact?tags=rr-forks

Thanks in advance.
