### ISSUE TITLE
Files which names contain accents are not supported 

### ISSUE THREAD

**Issue by Haythem-Zd** [cifsd-team/cifsd#50]
Hello,

It looks like file names that contain accents (like á, é, è, í, ó, ú, ü, ñ...) are impossible to work with in cifsd-shared foders.
When I tried to copy a file named "dummyéa" from the PC (client) to the share, I have an "Invalid parameter" error.
And, when I tried to rename an existing file to add a letter with accent, I had a "Cannot allocate memory" error. Also, I had these logs from the kernel module:

> kcifsd: smb_get_name:616: absoulte name = /mnt/sda1/test
> kcifsd: convert_to_unix_name:310: new_name len = 15
> kcifsd: smb_get_name:616: absoulte name = /mnt/sda1/test▒
> kcifsd: smb_rename:769: rename /mnt/sda1/test -> /mnt/sda1/test▒
> kcifsd: cifsd_vfs_rename:911: oldname test, newname test▒
> kcifsd: cifsd_vfs_rename:954: test▒ lookup failed with error = -84
> kcifsd: __process_request:167: Failed to process 7 [-84]

Is there a way to wrok around this?
Thanks,

Haythem

**Comment by sergey-senozhatsky** [comment]
On (04/03/19 07:44), Haythem-Zd wrote:
>    Hello,
> 
>    It looks like file names that contain accents (like á, é, è, í, ó, ú, ü,
>    ñ...) are impossible to work with in cifsd-shared foders.
>    When I tried to copy a file named "dummyéa" from the PC (client) to the
>    share, I have an "Invalid parameter" error.
>    And, when I tried to rename an existing file to add a letter with accent,
>    I had a "Cannot allocate memory" error. Also, I had these logs from the
>    kernel module:
> 
>      kcifsd: smb_get_name:616: absoulte name = /mnt/sda1/test
>      kcifsd: convert_to_unix_name:310: new_name len = 15
>      kcifsd: smb_get_name:616: absoulte name = /mnt/sda1/test▒
>      kcifsd: smb_rename:769: rename /mnt/sda1/test -> /mnt/sda1/test▒
>      kcifsd: cifsd_vfs_rename:911: oldname test, newname test▒
>      kcifsd: cifsd_vfs_rename:954: test▒ lookup failed with error = -84
>      kcifsd: __process_request:167: Failed to process 7 [-84]
> 
>    Is there a way to wrok around this?

Hi,

No workaround as of this moment; so let us take a look.

	-ss

**Comment by namjaejeon** [comment]
hm... I can copy dummyéa from windows(7,10) to cifsd share. Are you using the latest cifsd ?

**Comment by Haythem-Zd** [comment]
I was behind by few weeks. So I checked out today the master branches  of cifsd and cifs-tools. But I still have the same issue:

> root@myDevPC:/home/g179780# mount -t cifs --verbose //192.168.1.254/sda1/ /tmp/share/ -o user=haythem
> Password for haythem@//192.168.1.254/sda1/: 
> mount.cifs kernel mount options: ip=192.168.1.254,unc=\\192.168.1.254\sda1,user=haythem,pass=********
> root@myDevPC:/home/g179780# 
> root@myDevPC:/home/g179780# 
> root@myDevPC:/home/g179780# cd /tmp/share/
> root@myDevPC:/tmp/share# ls
> raspby.img  SAMBA  System Volume Information  test
> root@myDevPC:/tmp/share# 
> root@myDevPC:/tmp/share# mv test testé
> mv: cannot move ‘test’ to ‘testé’: Remote I/O error
> root@myDevPC:/tmp/share# 
> root@myDevPC:/tmp/share# 
> root@myDevPC:/tmp/share# cp /home/haythem/Desktop/dummyé .
> cp: cannot create regular file ‘./dummyé’: Input/output error

First I tried to rename the file "test" to "testé", then copy the file "dummyé" from my desktop to the share.
As you can see, both commands fail due to a I/O error.
On server side, I had these messages:

> kcifsd: cifsd_vfs_rename:976: test▒ lookup failed with error = -84
> kcifsd: cifsd_vfs_create:76: path create failed for /mnt/sda1/dummy▒, err -84


Also, after getting the latest version, I lost the guest acount access and now only users added by cifsadmin are granted access. My smb.conf file:

```
[global]
        netbios name = mytarget
        workgroup = home
        server string = mytarget Sharing Files
        map to guest = bad user
[sda1]
        comment = Share sda1 directory
        path = /mnt/sda1
        browsable = yes
        available = yes
        guest ok = yes
        writeable = yes
```

Usually, `map to guest = bad user` should do the trick. It is not working anymore.

**Comment by namjaejeon** [comment]
root@linkinjeon-Samsung-DeskTop-System:/mnt# mount.cifs -o vers=3.0,username=namjae,pass=1234 /.88.103.232/homes2 /mnt/read
root@linkinjeon-Samsung-DeskTop-System:/mnt# cd /mnt/read/
root@linkinjeon-Samsung-DeskTop-System:/mnt/read# cp /home/linkinjeon/test/dummyÃ©a .
root@linkinjeon-Samsung-DeskTop-System:/mnt/read# ls -al
total 131056
drwxr-xr-x 2 root root         0 Dec 31  1969 .
drwxr-xr-x 4 root root      4096 Jan 23 02:51 ..
-rwxr-xr-x 1 root root     59904 Dec 31  1969 dummyÃ©a
-rwxr-xr-x 1 root root 134192815 Jun  4  2015 linux-3.10.28.tgz
drwxr-xr-x 2 root root         0 Dec 31  1969 lost+found

hmm.. It work fine on my side. I think that it is character set issue on client side.

linkinjeon@linkinjeon-Samsung-DeskTop-System:~$ env | grep LANG
LANG=en_US.UTF-8
LANG is set with UTF-8 on my client PC, Could you check which character-set is used on your PC ?

> Usually, map to guest = bad user should do the trick. It is not working anymore.

Ah, Thanks for reporting! I fixed and push the patch to master now.

**Comment by namjaejeon** [comment]
Ah, there is iocharset option in cifs mount.
Could you try to add iocharset option in mount ?
e.g. mount -t cifs --verbose -o iocharset=utf8 //192.168.1.254/sda1/ /tmp/share/ -o user=haythem

**Comment by Haythem-Zd** [comment]
My client PC's LANG is set to` en_US.UTF-8` too. I think it is because of the target (server side) which is an embedded device with limited resources (Custom embedded Linux + busybox). I already had issues with the UTF16 charsets in cifsd user space (It always fallback to USC-2). 

If you have no further suggestions/ideas about this you can close this issue.

PS: the last revert in cifs-tools brought back the guest access. Thanks :)

**Comment by namjaejeon** [comment]
Ah, Okay, I would like to check last points. Could you tell me which CONFIG_NLS_DEFAULT is set in your kernel config ? and let me know your linux kernel version.
