### ISSUE TITLE
Non-english characters can not be used in share name?

### ISSUE THREAD

**Issue by iamwudy** [cifsd-team/cifsd#515]
I have such config file:
====start====
#/etc/ksmbd/smb.conf
[global]
        netbios name = SMBD

[阿]
        path = /SnapDisk1/阿
        valid users = wudy
        write list = wudy
====end====
Where "阿" is a (chinese) non-english character

When I visit the ksmbd server, both in Linux & Windows clients.
I got an error meaning "share list error"

If I change the config file as:
====start====
#/etc/ksmbd/smb.conf
[global]
        netbios name = SMBD

[aaa]
        path = /SnapDisk1/阿
        valid users = wudy
        write list = wudy
====end====
The error will disappear, and I will see the share folder "aaa"

If I change the config file as:
====start====
#/etc/ksmbd/smb.conf
[global]
        netbios name = SMBD

[ん]
        path = /SnapDisk1/阿
        valid users = wudy
        write list = wudy
====end====
Where "ん" is a (japanese) non-english character
The error appears again

Environment:
Arch: x86_64
OS: Centos 8
Kernel: 5.4.44

I have checked that: smb.conf is in UTF-8 and UTF-8 charset had compiled in kernel
And I have tested that the error is not in account/password phase

**Comment by namjaejeon** [comment]
@hclee Hyunchul, Can you take a look ?

**Comment by hclee** [comment]
Okay, I will take a look at this problem.

2021년 4월 23일 (금) 오전 8:39, Namjae Jeon ***@***.***>님이 작성:

**Comment by namjaejeon** [comment]
@iamwudy  Hi, Can you check your problem is fixed with #ksmbd-tools-next branch ?
git clone --branch=ksmbd-tools-next https://github.com/cifsd-team/ksmbd-tools

**Comment by iamwudy** [comment]
I will check it as quickly.

**Comment by iamwudy** [comment]
It works!
I have checked some Chinese, Korean and Japanese characters with listing $IPC and creating in share.
But I can't  ensure that it works on all characters. (Such as Greek)

**Comment by namjaejeon** [comment]
Thanks for your check!! If you paste Greek word you tested here, @hclee will check it.

**Comment by hclee** [comment]
@iamwudy
If you have problem with some languages, let me know these.
