### ISSUE TITLE
foobar2000 not working properly

### ISSUE THREAD

**Issue by neheb** [cifsd-team/cifsd#79]
This is the error from foobar2000's console

```
Folder watching failure: The specified server cannot perform the requested operation.  
Watching: X:\
```

I have no idea how this is implemented.

I asked on IRC how to debug foobar2000. I ended up getting this link to a Samba patch:
https://forum.synology.com/enu/viewtopic.php?f=111&t=27527#p108836

Not sure if applicable.

**Comment by namjaejeon** [comment]
Could you please provide both cifsd debug message and tcpdump ?

**Comment by namjaejeon** [comment]
It's probably because smb2 notify does not support it yet. I want to check it with dump information.

**Comment by neheb** [comment]
I checked the cifsd code, I think it implements what the patch does.

cifsd debug is kind of difficult as it slows everything down to a crawl before foobar2000 has a chance to error. I'll try to get tcpdump when I can.

My other theory was CONFIG_INOTIFY_USER missing but it's there. CONFIG_FANOTIFY however is not. I'll try that next.

**Comment by neheb** [comment]
Here's a log (quite big)
[cifs.gz](https://github.com/cifsd-team/cifsd/files/3123272/cifs.gz)

**Comment by namjaejeon** [comment]
Ah, It doesn't work with samba ? If no, You can check it after change notify is disable with samba.

change notify (G) 
This parameter specifies whether Samba should reply to a client's file change notify requests. 
You should never need to change this parameter
Default: change notify = yes

If same problem happen with samba after change notify = no, It is smb2 notify support issue.
Need to check double with tcpdump also.

**Comment by neheb** [comment]
Here's a partial log: 
[cif.gz](https://github.com/cifsd-team/cifsd/files/3123356/cif.gz)

Samba is fine with relatively default settings. So that might be it.

**Comment by namjaejeon** [comment]
Okay, I will check this issue in office.

**Comment by namjaejeon** [comment]
I installed foobar v1.4.3(https://www.foobar2000.org/download) in cifsd share and can see it work fine.  Am I missing something to reproduce issue ?

**Comment by neheb** [comment]
Add the share under Preferences > Media Library

Under Status. Mine shows Error!

The Console (View > Console) shows "Folder watching failure: The system cannot find the path specified.  "

**Comment by namjaejeon** [comment]
I fixed this issue and pushed the patch to the master branch. You can see "idle" status instead of "Error". It is same behavior with samba configured change notify = no in smb.conf. cifsd should support smb2 notify to be shown with "monitoring" status from foobar2000. We are planning to support it in this year.

**Comment by neheb** [comment]
Yep. Media Library is being populated again, albeit somewhat slowly. Though that's probably this powerline networking connection running at 5MB/s...

Closing.
