### ISSUE TITLE
Delay when access shares by a Windows 7 client

### ISSUE THREAD

**Issue by Haythem-Zd** [cifsd-team/cifsd#97]
Hello,

It has been notices that it can take more than a minute to open shares from a Windows 7 client machine. Such delay does not exist with Windows 10. 
Wireshark traces shows that Win7 client tries to request a **wkssvc rpc** and get stuck there for a while, then it requests a **srvsvc rpc** and everything goes fine.
Is this related to SMB versions used by different Windows clients?

Thanks,
Haythem

**Comment by sergey-senozhatsky** [comment]
On (05/27/19 02:02), Haythem-Zd wrote:
[..]
>    Wireshark traces shows that Win7 client tries to request a wkssvc rpc and
>    get stuck there for a while, then it requests a srvsvc rpc and everything
>    goes fine.
>    Is this related to SMB versions used by different Windows clients?

Hmm. We don't support wkssvc RPC, only srvsvc.

	-ss

**Comment by sergey-senozhatsky** [comment]
> It has been notices that it can take more than a minute to open shares from a Windows 7 client machine.

A variable or a constant dealy?

-ss

**Comment by Haythem-Zd** [comment]
It is reported to be around 1 minutes

**Comment by namjaejeon** [comment]
@sergey-senozhatsky As I remember, cifd-tools v1 supported wkssvc's pipe before, and it is removed when upgraded to v2. can we take wkssvc codes from v1 ?

**Comment by sergey-senozhatsky** [comment]
On (05/27/19 05:21), Namjae Jeon wrote:
>    can we take wkssvc codes from v1 ?

No, we cannot.

Can you reproduce them delays with your Win7 setup? Because
I don't see any delays, and never had. Windows 7 is my only
Windows test machine. Had there been a minute long delays
I would have noticed.

	-ss

**Comment by sergey-senozhatsky** [comment]
> It is reported to be around 1 minutes

@Haythem-Zd

Any chance I can take a look at smb.conf and/or wireshark trace file?

-ss

**Comment by Haythem-Zd** [comment]
Yeah sure.

The smb.conf looks like this:
```
[global]
        netbios name = mytarget
        workgroup = home
        server string = mytarget Sharing Files
        map to guest = bad user
[sda1]
        comment = Share sda1 directory
        path = /mnt/sda1
        browsable = yes
        available = yes
        guest ok = yes
        writeable = yes
```
Wireshark trace file:

[smb_w7.txt](https://github.com/cifsd-team/cifsd/files/3226085/smb_w7.txt)
*Github does not recognize .pcapng file extension so I renamed it to txt file

**Comment by sergey-senozhatsky** [comment]
Does anything chage if add you the following code to create_smb2_pipe()?

---

diff --git a/smb2pdu.c b/smb2pdu.c
index 4dfc6c7..dbf847a 100644
--- a/smb2pdu.c
+++ b/smb2pdu.c
@@ -1695,6 +1695,12 @@ static noinline int create_smb2_pipe(struct cifsd_work *work)
                goto out;
        }
 
+       if (!strcmp(name, "\\wkssvc") || !strcmp(name, "wkssvc")) {
+               err = -EINVAL;
+               kfree(name);
+               goto out;
+       }
+
        id = cifsd_session_rpc_open(work->sess, name);
        if (id < 0)
                cifsd_err("Unable to open RPC pipe: %d\n", id);

**Comment by sergey-senozhatsky** [comment]
FYI,

I'm working on a minimal wkssvc support. Will take me a day or two.

-ss

**Comment by Haythem-Zd** [comment]
@sergey-senozhatsky 
No change in connection time after applying your patch. But there is no more NOT_SUPPORTED answer by the cifsd server.

**Comment by sergey-senozhatsky** [comment]
@Haythem-Zd 
OK, scratch that kcifsd change.

I have the very naive (initial) wkssvc netwkstainfo100 implementation support for cifsd-tools. I just sent a patch [PATCH] cifsd-tools: wkssvc_NetWkstaInfo100 initial version

Can you give it a try?
A naive solution at this point, will improve it later on.

-ss

**Comment by Haythem-Zd** [comment]
@sergey-senozhatsky 
Thank you for your patch. It seems to be working as it reduced access time considerably and now we have the same behavior as Win10.
I will close this issue

**Comment by sergey-senozhatsky** [comment]
On (05/28/19 08:25), Haythem-Zd wrote:
>    [1]@sergey-senozhatsky
>    Thank you for your patch. It seems to be working as it reduced access time
>    considerably and now we have the same behavior as Win10.
>    I will close this issue

OK, thanks!
There will be more changes/improvements in this department.

	-ss
